# Generated by Django 3.1.2 on 2020-10-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='name',
        ),
    ]
