# Generated by Django 3.1.2 on 2020-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_fish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='name',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
